# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espai', '__first__'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comoponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(choices=[('n', 'normal'), ('o', 'organic')], default='n', max_length=1)),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.TextField()),
                ('datacompra', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuantitatsComponets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultiu.Comoponent')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultiu.Producte')),
                ('unitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UnitatMesura')),
            ],
        ),
        migrations.CreateModel(
            name='RegComponets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.FloatField()),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultiu.Producte')),
            ],
        ),
        migrations.CreateModel(
            name='TipologiesTractament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tractament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descripcio', models.TextField(blank=True, default='')),
                ('plantacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.Plantacio')),
                ('productes', models.ManyToManyField(through='cultiu.RegComponets', to='cultiu.Producte')),
            ],
        ),
        migrations.AddField(
            model_name='regcomponets',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultiu.Tractament'),
        ),
        migrations.AddField(
            model_name='regcomponets',
            name='unitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UnitatMesura'),
        ),
        migrations.AddField(
            model_name='producte',
            name='components',
            field=models.ManyToManyField(blank=True, through='cultiu.QuantitatsComponets', to='cultiu.Comoponent'),
        ),
    ]
