# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.FloatField()),
                ('tipologia', models.CharField(choices=[('s', 'Sodi'), ('l', 'Led')], max_length=1)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datainici', models.DateField()),
                ('datafinal', models.DateField(null=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.Focus')),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitatProducio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.TextField(blank=True, default='')),
                ('ubicacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.Ubicacio')),
            ],
        ),
        migrations.AddField(
            model_name='plantacio',
            name='tipologiaTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.TipologiaTest'),
        ),
        migrations.AddField(
            model_name='plantacio',
            name='unitatproducio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.UnitatProducio'),
        ),
    ]
