# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cannavis', '__first__'),
        ('espai', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='consum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantitat', models.IntegerField()),
                ('aportacio', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannavis.Lots')),
            ],
        ),
        migrations.CreateModel(
            name='previsiocultiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datainici', models.DateField(auto_now_add=True)),
                ('datafi', models.DateField()),
                ('quantitat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50, null=True)),
                ('poblacio', models.CharField(max_length=60, null=True)),
                ('telefon', models.CharField(max_length=12, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='UnitatMesura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='previsiocultiu',
            name='soci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Soci'),
        ),
        migrations.AddField(
            model_name='consum',
            name='soci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Soci'),
        ),
        migrations.AddField(
            model_name='consum',
            name='ubicacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espai.Ubicacio'),
        ),
    ]
